### ISSUE TITLE
CPAN?

### ISSUE THREAD

**Issue by perigrin** [carwynmoore/perl-nats#4]
The last release was removed from CPAN and I was just curious as to the reason why?

**Comment by carwynmoore** [comment]
I haven't touched anything on CPAN in a long time, has something changed?  Are you referring to a version thats not v0.2.0?

**Comment by perigrin** [comment]
Hmm this may be a false alarm, looks like there may be abut in metacpan.org, it's reporting the 0.2.0 release as having been removed. I'll go talk with them.

**Comment by perigrin** [comment]
Sorry about that. Originally https://metacpan.org/author/CARWYNM was claiming you'd removed everything. The metacpan people fixed their error. I'll just close this and pretend I'm not a twit :)
