### ISSUE TITLE
compile-time error in v0.2.1

### ISSUE THREAD

**Issue by dwburke** [carwynmoore/perl-nats#6]
Global symbol "$SSL_ERROR" requires explicit package name (did you forget to declare "my $SSL_ERROR"?) at /home/dburke/.plenv/versions/5.22.2/lib/perl5/site_perl/5.22.2/Net/NATS/Connection.pm line 45.

I have tested on perl versions 5.28.1 and 5.22.2
IO::Socket::SSL is updated to latest version as well

reproduce:
```
perl -MNet::NATS::Client
```

**Comment by rdapgar** [comment]
Maybe you can fix the problem by change the variable $SSL_ERROR to $IO::Socket::SSL::SSL_ERROR
Alternatively insert the line "use IO::Socket::SSL;" after "use strict;" at the beginning of Connection.pm.

**Comment by carwynmoore** [comment]
Thanks for raising the issue!  I've merged in the pull request fix 👍

**Comment by dshadow** [comment]
Hi! Could you please upload new version to CPAN ? Thanks!

**Comment by carwynmoore** [comment]
> Hi! Could you please upload new version to CPAN ? Thanks!

I've uploaded v0.2.2 to CPAN, ta for the reminder! 🙂
